#!/bin/bash

# C++
#export PRE='clang++-3.8 -std=c++11 -Wno-c++11-extensions
export  PRE='g++ -std=gnu++11 -fopenmp
  -Wall -Winit-self -Wmissing-include-dirs -Wswitch-default -Wswitch-enum
  -Wstrict-aliasing=2 -Wextra -Wundef -Wpointer-arith -Wunused-parameter
  -Wcast-qual -Wcast-align -Wwrite-strings -Wredundant-decls -Wconversion
  -I../../src
  -I/usr/include/GL
  -I../../libtk
  -L../../libtk
  -pedantic
  -O3 -funroll-loops -ffast-math
  -s'
export POST='-ltk -lX11 -lGL'

# Compile
/bin/rm -rf build
mkdir build
cd build

$PRE ../rotate.cc -o rotate $POST
$PRE ../shapes.cc -o shapes $POST
$PRE ../simple.cc -o simple $POST

cd ..
